### ISSUE TITLE
SP Link serial coms specification

### ISSUE THREAD

**Issue by expandstudios** [angus-g/splink-influx#1]
Hi Angus, not so much an issue as a question here. I would like to build an arduino-based server to expose SP Pro data to a local network so that clients can be configured with relays to switch appliances on or off based on certain parameters. Seems the serial coms port is probably the best way to get info out of the unit, do you have a specification for the protocol?

I can reverse engineer a fair bit of it from your code but I would prefer to have documentation.

Thanks
Russell

**Comment by angus-g** [comment]
I don't have a full specification, but I can provide some notes that I used for this project. Below are just the basics of packet structure, obtaining a connection and authentication. From here, you just need to know the addresses to query for certain parameters (e.g. 1 word from `0x0000A05C` will give the battery voltage), and some scaling constants to get these values to sensible units.

## Wire protocol
RS232 signalling (+3 to +15V for a 0 value, -15 to -3V for a 1 value), default baud rate of 57600 and 8N1. Packets consist of a header, optionally followed by a data payload. The word size is typically 16-bit.

## Header and data
The header is a fixed 8-byte field:

Bytes | Value
----- | -----
0 | Query (`0x51`, i.e. `Q`) or Write (`0x57`, i.e. `W`)
1 | Length in 16-bit words minus 1
2-5 | Address to access (little-endian)
6-7 | CRC-16-CCITT of header

Queries are sent as only the 8-byte header, and responded to with the header intact (importantly, retaining the `Q` flag). Data in query responses and write requests is placed directly in the packet, followed by another CRC-16-CCITT of only the data (excluding the header).

## Establishing a connection
To establish a connection, a query is sent to `0x0000A000` to obtain either the COM port we are communicating with (1 or 2), or `0xFF`, indicating authentication is required.

### Authentication
1. Query for an 8-word challenge hash from `0x001F0000`
2. Append the password to the challenge, pad to 32 bytes with spaces and compute MD5.
3. Write the new hash back to `0x001F0000`
4. Query `0x001F0010` indicates 1 in the first byte for successful authentication.

## Disconnecting
You should write 1 to `0x0000A00D` (or `0x0000A00E` depending on COM port?) to disconnect.

## Scaling constants

- **Signed DC voltage**: scale by 958.0 / 327680.0
- **Signed DC current**: scale by 10738.0 (I think)
- **Signed AC power**: scale by 4798.0 * (2000.0 / 3276800.0)

(there are some others, like frequency and 32-bit values)

**Comment by expandstudios** [comment]
Hi Angus, cheers for that! Certainly got enough to get started between the above and your codebase. Thanks.
